[[redirects]]
from = "https://www.nickfalcone.net"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "https://nickfalcone.net"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "http://www.nickfalcone.net"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "http://nickfalcone.net"
to = "https://www.nickfalcone.com"
status = 301
force = false