[[redirects]]
from = "https://www.nickfalcone.io"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "https://nickfalcone.io"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "http://www.nickfalcone.io"
to = "https://www.nickfalcone.com"
status = 301
force = false

[[redirects]]
from = "http://nickfalcone.io"
to = "https://www.nickfalcone.com"
status = 301
force = false